<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TitanFx.DependencyProperty.WinUI\TitanFx.DependencyProperty.WinUI.csproj">
      <PrivateAssets>all</PrivateAssets>
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\WinUI.Stubs\WinUI.Stubs.csproj" />
  </ItemGroup>
</Project>
