<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>System.Windows</RootNamespace>
    <NoWarn>$(NoWarn);IDE0060;CA1822</NoWarn>
  </PropertyGroup>
</Project>
