//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::System.Windows.DependencyPropertyKey IdPropertyKey
        = global::System.Windows.DependencyProperty.RegisterReadOnly(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial int Id 
    {
        get => (int)GetValue(IdPropertyKey.DependencyProperty);
    }
    #endregion Id
}
