//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::System.Windows.DependencyProperty IdProperty
        = global::System.Windows.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: static (sender, eventArgs) => 
                {
                    // TODO: Implement one of the following signatures:
                    global::MyComponent.HandleValueChanged(sender, eventArgs);
                    global::MyComponent.HandleValueChanged((global::MyComponent)sender, eventArgs);
                    ((global::MyComponent)sender).HandleValueChanged(eventArgs);
                    global::MyComponent.HandleValueChanged(sender, (int)eventArgs.NewValue, (int)eventArgs.OldValue);
                    global::MyComponent.HandleValueChanged((global::MyComponent)sender, (int)eventArgs.NewValue, (int)eventArgs.OldValue);
                    ((global::MyComponent)sender).HandleValueChanged((int)eventArgs.NewValue, (int)eventArgs.OldValue);
                    global::MyComponent.HandleValueChanged(sender, (int)eventArgs.NewValue);
                    global::MyComponent.HandleValueChanged((global::MyComponent)sender, (int)eventArgs.NewValue);
                    ((global::MyComponent)sender).HandleValueChanged((int)eventArgs.NewValue);
                    global::MyComponent.HandleValueChanged(sender);
                    global::MyComponent.HandleValueChanged((global::MyComponent)sender);
                    ((global::MyComponent)sender).HandleValueChanged();
                    throw new global::System.NotImplementedException("A callback was specified but not implemented");
                },
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    static partial void HandleValueChanged(global::System.Windows.DependencyObject target, global::System.Windows.DependencyPropertyChangedEventArgs e);
    static partial void HandleValueChanged(global::MyComponent target, global::System.Windows.DependencyPropertyChangedEventArgs e);
    partial void HandleValueChanged(global::System.Windows.DependencyPropertyChangedEventArgs e);
    static partial void HandleValueChanged(global::System.Windows.DependencyObject target, int newValue, int oldValue);
    static partial void HandleValueChanged(global::MyComponent target, int newValue, int oldValue);
    partial void HandleValueChanged(int newValue, int oldValue);
    static partial void HandleValueChanged(global::System.Windows.DependencyObject target, int newValue);
    static partial void HandleValueChanged(global::MyComponent target, int newValue);
    partial void HandleValueChanged(int newValue);
    static partial void HandleValueChanged(global::System.Windows.DependencyObject target);
    static partial void HandleValueChanged(global::MyComponent target);
    partial void HandleValueChanged();
    #endregion Id
}
