//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region IsSuccess
    public static readonly global::System.Windows.DependencyProperty IsSuccessProperty
        = global::System.Windows.DependencyProperty.RegisterAttached(
            "IsSuccess",
            typeof(bool),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(bool),
                propertyChangedCallback: static (sender, eventArgs) => 
                {
                    // TODO: Implement one of the following signatures:
                    global::MyComponent.HandleIsSuccessChanged(sender, eventArgs);
                    global::MyComponent.HandleIsSuccessChanged((global::System.Windows.FrameworkElement)sender, eventArgs);
                    global::MyComponent.HandleIsSuccessChanged(sender, (bool)eventArgs.NewValue, (bool)eventArgs.OldValue);
                    global::MyComponent.HandleIsSuccessChanged((global::System.Windows.FrameworkElement)sender, (bool)eventArgs.NewValue, (bool)eventArgs.OldValue);
                    global::MyComponent.HandleIsSuccessChanged(sender, (bool)eventArgs.NewValue);
                    global::MyComponent.HandleIsSuccessChanged((global::System.Windows.FrameworkElement)sender, (bool)eventArgs.NewValue);
                    global::MyComponent.HandleIsSuccessChanged(sender);
                    global::MyComponent.HandleIsSuccessChanged((global::System.Windows.FrameworkElement)sender);
                    throw new global::System.NotImplementedException("A callback was specified but not implemented");
                },
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public static partial bool GetIsSuccess(global::System.Windows.FrameworkElement target);
    public static partial bool GetIsSuccess(global::System.Windows.FrameworkElement target)
    {
        return (bool)target.GetValue(global::MyComponent.IsSuccessProperty);
    }
    public static partial void SetIsSuccess(global::System.Windows.FrameworkElement target, bool value);
    public static partial void SetIsSuccess(global::System.Windows.FrameworkElement target, bool value)
    {
        target.SetValue(global::MyComponent.IsSuccessProperty, value);
    }
    static partial void HandleIsSuccessChanged(global::System.Windows.DependencyObject target, global::System.Windows.DependencyPropertyChangedEventArgs e);
    static partial void HandleIsSuccessChanged(global::System.Windows.FrameworkElement target, global::System.Windows.DependencyPropertyChangedEventArgs e);
    static partial void HandleIsSuccessChanged(global::System.Windows.DependencyObject target, bool newValue, bool oldValue);
    static partial void HandleIsSuccessChanged(global::System.Windows.FrameworkElement target, bool newValue, bool oldValue);
    static partial void HandleIsSuccessChanged(global::System.Windows.DependencyObject target, bool newValue);
    static partial void HandleIsSuccessChanged(global::System.Windows.FrameworkElement target, bool newValue);
    static partial void HandleIsSuccessChanged(global::System.Windows.DependencyObject target);
    static partial void HandleIsSuccessChanged(global::System.Windows.FrameworkElement target);
    #endregion IsSuccess
}
public static partial class MyComponent_Extensions
{
    extension(global::System.Windows.FrameworkElement target)
    {
        public bool IsSuccess
        {
            get => global::MyComponent.GetIsSuccess(target);
            set => global::MyComponent.SetIsSuccess(target, value);
        }
    }
}
