//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region IsSuccess
    public static readonly global::System.Windows.DependencyProperty IsSuccessProperty
        = global::System.Windows.DependencyProperty.RegisterAttached(
            "IsSuccess",
            typeof(bool),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(bool),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public static partial bool GetIsSuccess(global::System.Windows.FrameworkElement target);
    public static partial bool GetIsSuccess(global::System.Windows.FrameworkElement target)
    {
        return (bool)target.GetValue(global::MyComponent.IsSuccessProperty);
    }
    public static partial void SetIsSuccess(global::System.Windows.FrameworkElement target, bool value);
    public static partial void SetIsSuccess(global::System.Windows.FrameworkElement target, bool value)
    {
        target.SetValue(global::MyComponent.IsSuccessProperty, value);
    }
    #endregion IsSuccess
}
public static partial class MyComponent_Extensions
{
    extension(global::System.Windows.FrameworkElement target)
    {
        public bool IsSuccess
        {
            get => global::MyComponent.GetIsSuccess(target);
            set => global::MyComponent.SetIsSuccess(target, value);
        }
    }
}
