//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Content
    public static readonly global::System.Windows.DependencyProperty ContentProperty
        = global::System.Windows.DependencyProperty.Register(
            "Content",
            typeof(global::System.Windows.FrameworkElement),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(global::System.Windows.FrameworkElement),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial global::System.Windows.FrameworkElement? Content 
    {
        get => (global::System.Windows.FrameworkElement?)GetValue(ContentProperty);
        set => SetValue(ContentProperty, value); 
    }
    #endregion Content
    #region Id
    public static readonly global::System.Windows.DependencyProperty IdProperty
        = global::System.Windows.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
    #region Source
    public static readonly global::System.Windows.DependencyProperty SourceProperty
        = global::System.Windows.DependencyProperty.Register(
            "Source",
            typeof(string),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(string),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial string Source 
    {
        get => (string)GetValue(SourceProperty);
        set => SetValue(SourceProperty, value); 
    }
    #endregion Source
}
