//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::System.Windows.DependencyProperty IdProperty
        = global::System.Windows.DependencyProperty.Register(
            "Id",
            typeof(string),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: global::MyComponent.GetInitialId(),
                propertyChangedCallback: null,
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial string Id 
    {
        get => (string)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
}
