//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::System.Windows.DependencyProperty IdProperty
        = global::System.Windows.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::System.Windows.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: static (sender, eventArgs) => 
                    global::MyComponent.HandleValueChanged(
                        (global::MyComponent)sender
                    ),
                coerceValueCallback: null
                
            ),
            validateValueCallback: null
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
}
