<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TitanFx.DependencyProperty.Wpf\TitanFx.DependencyProperty.Wpf.csproj">
      <PrivateAssets>all</PrivateAssets>
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\Wpf.Stubs\Wpf.Stubs.csproj" />
  </ItemGroup>
</Project>
