//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: static (sender, eventArgs) => 
                    ((global::MyComponent)sender).HandleValueChanged(
                        (int)eventArgs.NewValue
                    )
            )
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
}
