//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region IsSuccess
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IsSuccessProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.RegisterAttached(
            "IsSuccess",
            typeof(bool),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: typeof(bool)
            )
        );
    public static partial bool GetIsSuccess(global::Microsoft.UI.Xaml.FrameworkElement target);
    public static partial bool GetIsSuccess(global::Microsoft.UI.Xaml.FrameworkElement target)
    {
        return (bool)target.GetValue(global::MyComponent.IsSuccessProperty);
    }
    public static partial void SetIsSuccess(global::Microsoft.UI.Xaml.FrameworkElement target, bool value);
    public static partial void SetIsSuccess(global::Microsoft.UI.Xaml.FrameworkElement target, bool value)
    {
        target.SetValue(global::MyComponent.IsSuccessProperty, value);
    }
    #endregion IsSuccess
}
static partial class MyComponent_Extensions
{
    extension(global::Microsoft.UI.Xaml.FrameworkElement target)
    {
        public bool IsSuccess
        {
            get => global::MyComponent.GetIsSuccess(target);
            set => global::MyComponent.SetIsSuccess(target, value);
        }
    }
}
