//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Content
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty ContentProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Content",
            typeof(global::Microsoft.UI.Xaml.FrameworkElement),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(global::Microsoft.UI.Xaml.FrameworkElement),
                propertyChangedCallback: null
            )
        );
    public partial global::Microsoft.UI.Xaml.FrameworkElement? Content 
    {
        get => (global::Microsoft.UI.Xaml.FrameworkElement?)GetValue(ContentProperty);
        set => SetValue(ContentProperty, value); 
    }
    #endregion Content
    #region Id
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(int),
                propertyChangedCallback: null
            )
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
    #region Source
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty SourceProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Source",
            typeof(string),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(string),
                propertyChangedCallback: null
            )
        );
    public partial string Source 
    {
        get => (string)GetValue(SourceProperty);
        set => SetValue(SourceProperty, value); 
    }
    #endregion Source
}
