//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(int)
            )
        );
    public partial int Id {
        init => SetValue(IdProperty, value); 
    }
}
