//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty ContentProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Content",
            typeof(global::Microsoft.UI.Xaml.FrameworkElement),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: default(global::Microsoft.UI.Xaml.FrameworkElement)
            )
        );
    public partial global::Microsoft.UI.Xaml.FrameworkElement Content {
        get => (global::Microsoft.UI.Xaml.FrameworkElement)GetValue(ContentProperty);
        set => SetValue(ContentProperty, value); 
    }
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: (int)(123)
            )
        );
    public partial int Id {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty SourceProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Source",
            typeof(string),
            typeof(global::MyComponent),
            new global::Microsoft.UI.Xaml.PropertyMetadata(
                defaultValue: (string)("https://test.invalid/")
            )
        );
    public partial string Source {
        get => (string)GetValue(SourceProperty);
        set => SetValue(SourceProperty, value); 
    }
}
