//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(string),
            typeof(global::MyComponent),
            global::Microsoft.UI.Xaml.PropertyMetadata.Create(
                createDefaultValueCallback: global::MyComponent.GetInitialId
            )
        );
    public partial string Id 
    {
        get => (string)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
}
