//HintName: MyComponent.DependencyProperty.g.cs
// <auto-generated />
#nullable enable
partial class MyComponent
{
    #region Id
    public static readonly global::Microsoft.UI.Xaml.DependencyProperty IdProperty
        = global::Microsoft.UI.Xaml.DependencyProperty.Register(
            "Id",
            typeof(int),
            typeof(global::MyComponent),
            global::Microsoft.UI.Xaml.PropertyMetadata.Create(
                createDefaultValueCallback: static () => global::MyComponent.InitialId
            )
        );
    public partial int Id 
    {
        get => (int)GetValue(IdProperty);
        set => SetValue(IdProperty, value); 
    }
    #endregion Id
}
