using System.CodeDom.Compiler;
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TitanFx.DependencyProperty.WinUI.Model;
using static TitanFx.DependencyProperty.WinUI.Model.Constants;

namespace TitanFx.DependencyProperty.WinUI;

internal static class DependencyPropertyGenerator
{
    public static void Emit(
        IncrementalGeneratorInitializationContext context,
        IncrementalValuesProvider<DependencyObjectInfo> dependencyObjects
    )
    {
        context.RegisterSourceOutput(dependencyObjects, Generate);
    }

    private static void Generate(SourceProductionContext context, DependencyObjectInfo source)
    {
        context.AddSource(
            $"{source.Type.Replace("global::", "").Replace('<', '[').Replace('>', ']')}.DependencyProperty.g.cs",
            WriteSource(source)
        );
    }

    private static string WriteSource(DependencyObjectInfo source)
    {
        var result = new StringWriter();
        using var output = new IndentedTextWriter(result);

        output.WriteLine("// <auto-generated />");
        output.WriteLine("#nullable enable");

        if (source.Namespace is not null)
            output.WriteLine($"namespace {source.Namespace};");

        foreach (var type in source.Path)
        {
            if (type.Modifiers is not "")
                output.Write($"{type.Modifiers} ");
            output.WriteLine($"partial {type.Kind} {type.Name}{type.TypeParameters}");
            output.WriteLine("{");
            output.Indent++;
        }

        foreach (var property in source.Properties)
        {
            WriteDependencyProperty(output, source.Type, property);
            WriteInstanceProperty("", output, property);
        }

        foreach (var _ in source.Path)
        {
            output.Indent--;
            output.WriteLine("}");
        }

        return result.ToString();
    }

    private static void WriteInstanceProperty(
        string @this,
        IndentedTextWriter output,
        DependencyPropertyInfo property
    )
    {
        WriteModifiers(output, property.Modifiers);
        output.WriteLine($"{property.PropertyType} {property.Name} {{");
        output.Indent++;
        if (property.GetterModifiers is { } get)
        {
            WriteModifiers(output, get);
            output.WriteLine(
                $"get => ({property.PropertyType}){@this}GetValue({property.Name}Property);"
            );
        }
        if (property.SetterModifiers is { } set)
        {
            WriteModifiers(output, set);
            output.WriteLine($"set => {@this}SetValue({property.Name}Property, value); ");
        }
        if (property.InitModifiers is { } init)
        {
            WriteModifiers(output, init);
            output.WriteLine($"init => {@this}SetValue({property.Name}Property, value); ");
        }
        output.Indent--;
        output.WriteLine("}");
    }

    private static void WriteDependencyProperty(
        IndentedTextWriter output,
        string ownerType,
        DependencyPropertyInfo property
    )
    {
        output.WriteLine(
            $"public static readonly {Types.DependencyProperty} {property.Name}Property"
        );
        output.Indent++;
        output.WriteLine($"= {Types.DependencyProperty}.Register(");
        output.Indent++;
        output.WriteLine($"{SymbolDisplay.FormatLiteral(property.Name, true)},");
        output.WriteLine($"typeof({property.PropertyType}),");
        output.WriteLine($"typeof({ownerType}),");
        WriteNewPropertyMetadata(output, ownerType, property);
        output.Indent--;
        output.WriteLine(");");
        output.Indent--;
    }

    private static void WriteNewPropertyMetadata(
        IndentedTextWriter output,
        string ownerType,
        DependencyPropertyInfo property
    )
    {
        if (property.CreateDefaultValue is null)
        {
            output.WriteLine($"new {Types.PropertyMetadata}(");
            output.Indent++;
            output.Write($"defaultValue: {property.InitialValue}");
        }
        else
        {
            output.WriteLine($"{Types.PropertyMetadata}.Create(");
            output.Indent++;
            output.Write($"createDefaultValueCallback: {ownerType}.{property.CreateDefaultValue}");
        }

        if (
            property.OnValueChanged
            is not {
                Signature: not (
                    OnValueChangedSignature.NotFound
                    or OnValueChangedSignature.Unsupported
                )
            } vc
        )
            output.WriteLine();
        else if (vc.Signature is OnValueChangedSignature.DependencyObject_EventArgs)
        {
            output.WriteLine(",");
            output.WriteLine($"propertyChangedCallback: {ownerType}.{vc.MethodName}");
        }
        else
        {
            output.WriteLine(",");
            output.WriteLine("propertyChangedCallback: static (sender, eventArgs) => {");
            output.Indent++;
            switch (vc.Signature & OnValueChangedSignature.Sender)
            {
                case OnValueChangedSignature.This:
                    output.WriteLine($"(({ownerType})sender).{vc.MethodName}(");
                    output.Indent++;
                    break;
                case OnValueChangedSignature.DependencyObject:
                    output.WriteLine($"{ownerType}.{vc.MethodName}(");
                    output.Indent++;
                    output.Write("sender");
                    output.WriteLine(vc.Signature.HasFlag(OnValueChangedSignature.Only) ? "" : ",");
                    break;
                case OnValueChangedSignature.Owner:
                    output.WriteLine($"{ownerType}.{vc.MethodName}(");
                    output.Indent++;
                    output.Write($"({ownerType})sender");
                    output.WriteLine(vc.Signature.HasFlag(OnValueChangedSignature.Only) ? "" : ",");
                    break;
            }
            switch (vc.Signature & OnValueChangedSignature.Change)
            {
                case OnValueChangedSignature.EventArgs:
                    output.WriteLine("eventArgs");
                    output.Indent--;
                    output.WriteLine(");");
                    break;
                case OnValueChangedSignature.NewOld:
                    output.WriteLine($"({property.PropertyType})eventArgs.NewValue,");
                    output.WriteLine($"({property.PropertyType})eventArgs.OldValue");
                    output.Indent--;
                    output.WriteLine(");");
                    break;
                case OnValueChangedSignature.New:
                    output.WriteLine($"({property.PropertyType})eventArgs.NewValue");
                    output.Indent--;
                    output.WriteLine(");");
                    break;
                case OnValueChangedSignature.Only:
                    output.Indent--;
                    output.WriteLine(");");
                    break;
            }
            output.Indent--;
            output.WriteLine("}");
        }
        output.Indent--;
        output.WriteLine(")");
    }

    private static void WriteModifiers(IndentedTextWriter output, Modifiers? modifiers)
    {
        if (modifiers is null)
            return;
        var sep = "";
        if (modifiers.Accessibility is not null)
        {
            output.Write(modifiers.Accessibility);
            sep = " ";
        }
        foreach (var other in modifiers.Other)
        {
            output.Write(sep);
            sep = " ";
            output.Write(other);
        }
        output.Write(sep);
    }
}
