using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TitanFx.DependencyProperty.WinUI.Model;
using static TitanFx.DependencyProperty.WinUI.Model.Constants;

namespace TitanFx.DependencyProperty.WinUI;

internal static class DependencyPropertyGenerator
{
    public static void Emit(
        IncrementalGeneratorInitializationContext context,
        IncrementalValuesProvider<DependencyObjectInfo> dependencyObjects
    )
    {
        context.RegisterSourceOutput(dependencyObjects, Generate);
    }

    private static void Generate(SourceProductionContext context, DependencyObjectInfo source)
    {
        context.AddSource(
            $"{source.Type.Replace("global::", "").Replace('<', '[').Replace('>', ']')}.DependencyProperty.g.cs",
            WriteSource(source)
        );
    }

    private static string WriteSource(DependencyObjectInfo source)
    {
        var result = new StringWriter();
        using var output = new IndentedTextWriter(result);

        output.WriteLine("// <auto-generated />");
        output.WriteLine("#nullable enable");

        if (source.Namespace is not null)
            output.WriteLine($"namespace {source.Namespace};");

        foreach (var type in source.Path)
        {
            if (type.Modifiers is not "")
                output.Write($"{type.Modifiers} ");
            output.WriteLine($"partial {type.Kind} {type.Name}{type.TypeParameters}");
            output.WriteLine("{");
            output.Indent++;
        }

        var staticOnly = true;
        foreach (var property in source.AttachedProperties)
        {
            output.WriteLine($"#region {property.Name}");
            WriteDependencyProperty(
                output,
                "RegisterAttached",
                source.Type,
                property.TargetType,
                property,
                staticOnly
            );
            WriteAttachedGetter(output, source.Type, property);
            WriteAttachedSetter(output, source.Type, property);
            if (
                property.OnValueChanged is
                {
                    Signature: OnValueChangedSignature.NotFound
                        or OnValueChangedSignature.Unsupported,
                    MethodName: var onValueChanged
                }
            )
            {
                WriteOnValueChangedPotentialSignatures(
                    output,
                    property.TargetType,
                    property,
                    onValueChanged,
                    staticOnly
                );
            }
            output.WriteLine($"#endregion {property.Name}");
        }

        staticOnly = false;
        foreach (var property in source.Properties)
        {
            output.WriteLine($"#region {property.Name}");
            WriteDependencyProperty(
                output,
                "Register",
                source.Type,
                source.Type,
                property,
                staticOnly
            );
            WriteInstanceProperty(output, property);
            if (
                property.OnValueChanged is
                {
                    Signature: OnValueChangedSignature.NotFound
                        or OnValueChangedSignature.Unsupported,
                    MethodName: var onValueChanged
                }
            )
            {
                WriteOnValueChangedPotentialSignatures(
                    output,
                    source.Type,
                    property,
                    onValueChanged,
                    staticOnly
                );
            }
            output.WriteLine($"#endregion {property.Name}");
        }

        foreach (var _ in source.Path)
        {
            output.Indent--;
            output.WriteLine("}");
        }

        if (source.AttachedProperties.Count > 0)
        {
            WriteAttachedExtensionMethods(source, output);
        }

        return result.ToString();
    }

    private static void WriteAttachedExtensionMethods(
        DependencyObjectInfo source,
        IndentedTextWriter output
    )
    {
        var extensionClass = new StringBuilder();
        foreach (var type in source.Path)
        {
            _ = extensionClass.Append($"{type.Name}_");
        }

        output.Write(
            source.Visibility switch
            {
                Accessibility.Private => "private ",
                Accessibility.ProtectedAndInternal => "private protected ",
                Accessibility.Protected => "protected ",
                Accessibility.Internal => "internal ",
                Accessibility.ProtectedOrInternal => "protected internal ",
                Accessibility.Public => "public ",
                _ => "",
            }
        );

        output.WriteLine($"static partial class {extensionClass}Extensions");
        using (Util.WriteBlock(output))
        {
            foreach (var group in source.AttachedProperties.GroupBy(static x => x.TargetType))
            {
                output.WriteLine($"extension({group.Key} target)");
                using (Util.WriteBlock(output))
                {
                    foreach (var property in group)
                    {
                        output.WriteLine($"public {property.Type} {property.Name}");
                        using (Util.WriteBlock(output))
                        {
                            output.WriteLine($"get => {source.Type}.Get{property.Name}(target);");
                            output.WriteLine(
                                $"set => {source.Type}.Set{property.Name}(target, value);"
                            );
                        }
                    }
                }
            }
        }
    }

    private static void WriteOnValueChangedPotentialSignatures(
        IndentedTextWriter output,
        string targetType,
        DependencyPropertyInfoBase property,
        string methodName,
        bool staticOnly
    )
    {
        output.WriteLine(
            $"static partial void {methodName}({Types.DependencyObject} target, {Types.DependencyPropertyChangedEventArgs} e);"
        );
        output.WriteLine(
            $"static partial void {methodName}({targetType} target, {Types.DependencyPropertyChangedEventArgs} e);"
        );
        if (!staticOnly)
        {
            output.WriteLine(
                $"partial void {methodName}({Types.DependencyPropertyChangedEventArgs} e);"
            );
        }
        output.WriteLine(
            $"static partial void {methodName}({Types.DependencyObject} target, {property.Type} newValue, {property.Type} oldValue);"
        );
        output.WriteLine(
            $"static partial void {methodName}({targetType} target, {property.Type} newValue, {property.Type} oldValue);"
        );
        if (!staticOnly)
        {
            output.WriteLine(
                $"partial void {methodName}({property.Type} newValue, {property.Type} oldValue);"
            );
        }
        output.WriteLine(
            $"static partial void {methodName}({Types.DependencyObject} target, {property.Type} newValue);"
        );
        output.WriteLine(
            $"static partial void {methodName}({targetType} target, {property.Type} newValue);"
        );
        if (!staticOnly)
        {
            output.WriteLine($"partial void {methodName}({property.Type} newValue);");
        }
        output.WriteLine($"static partial void {methodName}({Types.DependencyObject} target);");
        output.WriteLine($"static partial void {methodName}({targetType} target);");
        if (!staticOnly)
        {
            output.WriteLine($"partial void {methodName}();");
        }
    }

    private static void WriteOnValueChangedPotentialCalls(
        IndentedTextWriter output,
        string ownerType,
        string targetType,
        DependencyPropertyInfoBase property,
        bool staticOnly,
        OnValueChangedInfo vc
    )
    {
        output.WriteLine($"{ownerType}.{vc.MethodName}(sender, eventArgs);");
        output.WriteLine($"{ownerType}.{vc.MethodName}(({targetType})sender, eventArgs);");
        if (!staticOnly)
        {
            output.WriteLine($"(({targetType})sender).{vc.MethodName}(eventArgs);");
        }
        output.WriteLine(
            $"{ownerType}.{vc.MethodName}(sender, ({property.Type})eventArgs.NewValue, ({property.Type})eventArgs.OldValue);"
        );
        output.WriteLine(
            $"{ownerType}.{vc.MethodName}(({targetType})sender, ({property.Type})eventArgs.NewValue, ({property.Type})eventArgs.OldValue);"
        );
        if (!staticOnly)
        {
            output.WriteLine(
                $"(({targetType})sender).{vc.MethodName}(({property.Type})eventArgs.NewValue, ({property.Type})eventArgs.OldValue);"
            );
        }
        output.WriteLine(
            $"{ownerType}.{vc.MethodName}(sender, ({property.Type})eventArgs.NewValue);"
        );
        output.WriteLine(
            $"{ownerType}.{vc.MethodName}(({targetType})sender, ({property.Type})eventArgs.NewValue);"
        );
        if (!staticOnly)
        {
            output.WriteLine(
                $"(({targetType})sender).{vc.MethodName}(({property.Type})eventArgs.NewValue);"
            );
        }
        output.WriteLine($"{ownerType}.{vc.MethodName}(sender);");
        output.WriteLine($"{ownerType}.{vc.MethodName}(({targetType})sender);");

        if (!staticOnly)
        {
            output.WriteLine($"(({targetType})sender).{vc.MethodName}();");
        }
    }

    private static void WriteAttachedSetter(
        IndentedTextWriter output,
        string ownerType,
        AttachedDependencyPropertyInfo property
    )
    {
        var signature =
            $"public static partial void Set{property.Name}({property.TargetType} target, {property.Type} value)";
        output.WriteLine($"{signature};");
        output.WriteLine(signature);
        using (Util.WriteBlock(output))
        {
            output.WriteLine($"target.SetValue({ownerType}.{property.Name}Property, value);");
        }
    }

    private static void WriteAttachedGetter(
        IndentedTextWriter output,
        string ownerType,
        AttachedDependencyPropertyInfo property
    )
    {
        var signature =
            $"public static partial {property.Type} Get{property.Name}({property.TargetType} target)";
        output.WriteLine($"{signature};");
        output.WriteLine(signature);
        using (Util.WriteBlock(output))
        {
            output.WriteLine(
                $"return ({property.Type})target.GetValue({ownerType}.{property.Name}Property);"
            );
        }
    }

    private static void WriteInstanceProperty(
        IndentedTextWriter output,
        DependencyPropertyInfo property
    )
    {
        WriteModifiers(output, property.Modifiers);
        output.WriteLine($"{property.Type} {property.Name} ");
        using (Util.WriteBlock(output))
        {
            if (property.GetterModifiers is { } get)
            {
                WriteModifiers(output, get);
                output.WriteLine($"get => ({property.Type})GetValue({property.Name}Property);");
            }
            if (property.SetterModifiers is { } set)
            {
                WriteModifiers(output, set);
                output.WriteLine($"set => SetValue({property.Name}Property, value); ");
            }
            if (property.InitModifiers is { } init)
            {
                WriteModifiers(output, init);
                output.WriteLine($"init => SetValue({property.Name}Property, value); ");
            }
        }
    }

    private static void WriteDependencyProperty(
        IndentedTextWriter output,
        string register,
        string ownerType,
        string targetType,
        DependencyPropertyInfoBase property,
        bool staticOnly
    )
    {
        output.WriteLine(
            $"public static readonly {Types.DependencyProperty} {property.Name}Property"
        );
        using (Util.Indent(output))
        {
            output.Write($"= {Types.DependencyProperty}.{register}");
            using (Util.WriteBlock(output, "(", ");"))
            {
                output.WriteLine($"{SymbolDisplay.FormatLiteral(property.Name, true)},");
                output.WriteLine($"typeof({property.RuntimeType}),");
                output.WriteLine($"typeof({ownerType}),");
                WriteNewPropertyMetadata(output, ownerType, targetType, property, staticOnly);
            }
        }
    }

    private static void WriteNewPropertyMetadata(
        IndentedTextWriter output,
        string ownerType,
        string targetType,
        DependencyPropertyInfoBase property,
        bool staticOnly
    )
    {
        if (property.CreateDefaultValue is null)
        {
            output.Write($"new {Types.PropertyMetadata}");
        }
        else
        {
            output.Write($"{Types.PropertyMetadata}.Create");
        }
        using (Util.WriteBlock(output, "(", ")"))
        {
            if (property.CreateDefaultValue is null)
            {
                output.Write($"defaultValue: default({property.RuntimeType})");
            }
            else
            {
                output.Write("createDefaultValueCallback: ");
                switch (property.CreateDefaultValue)
                {
                    case { IsMethod: false, Name: var name }:
                        output.Write($"static () => {ownerType}.{name}");
                        break;
                    case { ReturnsReferenceType: false, Name: var name }:
                        output.Write($"static () => {ownerType}.{name}()");
                        break;
                    case { Name: var name }:
                        output.Write($"{ownerType}.{name}");
                        break;
                }
            }

            if (property.OnValueChanged is not { } vc)
                output.WriteLine();
            else if (
                vc.Signature
                is OnValueChangedSignature.Unsupported
                    or OnValueChangedSignature.NotFound
            )
            {
                output.WriteLine(",");
                output.WriteLine("propertyChangedCallback: static (sender, eventArgs) => ");
                using (Util.WriteBlock(output))
                {
                    output.WriteLine("// TODO: Implement one of the following signatures:");
                    WriteOnValueChangedPotentialCalls(
                        output,
                        ownerType,
                        targetType,
                        property,
                        staticOnly,
                        vc
                    );
                }
            }
            else if (vc.Signature is OnValueChangedSignature.DependencyObject_EventArgs)
            {
                output.WriteLine(",");
                output.WriteLine($"propertyChangedCallback: {ownerType}.{vc.MethodName}");
            }
            else
            {
                output.WriteLine(",");
                output.WriteLine("propertyChangedCallback: static (sender, eventArgs) => ");
                using (Util.Indent(output))
                {
                    var sender = vc.Signature & OnValueChangedSignature.Sender;
                    var change = vc.Signature & OnValueChangedSignature.Change;
                    output.Write(
                        sender switch
                        {
                            OnValueChangedSignature.Owner =>
                                $"(({targetType})sender).{vc.MethodName}",
                            _ => $"{ownerType}.{vc.MethodName}",
                        }
                    );
                    using (Util.WriteBlock(output, "(", ")"))
                    {
                        if (sender is not OnValueChangedSignature.Owner)
                        {
                            if (sender is OnValueChangedSignature.DependencyObject)
                                output.Write("sender");
                            else if (sender is OnValueChangedSignature.Target)
                                output.Write($"({targetType})sender");
                            output.WriteLine(change is OnValueChangedSignature.Only ? "" : ",");
                        }
                        switch (change)
                        {
                            case OnValueChangedSignature.EventArgs:
                                output.WriteLine("eventArgs");
                                break;
                            case OnValueChangedSignature.NewOld:
                                output.WriteLine($"({property.Type})eventArgs.NewValue,");
                                output.WriteLine($"({property.Type})eventArgs.OldValue");
                                break;
                            case OnValueChangedSignature.New:
                                output.WriteLine($"({property.Type})eventArgs.NewValue");
                                break;
                            case OnValueChangedSignature.Only:
                                break;
                        }
                    }
                }
            }
        }
    }

    private static void WriteModifiers(IndentedTextWriter output, Modifiers? modifiers)
    {
        if (modifiers is null)
            return;
        var sep = "";
        if (modifiers.Accessibility is not null)
        {
            output.Write(modifiers.Accessibility);
            sep = " ";
        }
        foreach (var other in modifiers.Other)
        {
            output.Write(sep);
            sep = " ";
            output.Write(other);
        }
        output.Write(sep);
    }
}
