using Microsoft.CodeAnalysis;
using static TitanFx.DependencyProperty.WinUI.Model.Constants;

namespace TitanFx.DependencyProperty.WinUI;

internal static class UtilGenerator
{
    public static void Emit(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(Generate);
    }

    private static void Generate(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(
            "Util.g.cs",
            $$"""
            // <auto-generated />
            #nullable enable

            namespace {{Namespace}};

            [{{Types.EmbeddedAttribute}}]
            [{{Types.AttributeUsageAttribute}}({{Types.AttributeTargets}}.Property, AllowMultiple = false, Inherited = false)]
            internal sealed partial class {{DependencyPropertyAttribute}} : {{Types.Attribute}}
            {
                public {{Types.String}}? {{CreateDefaultValue}} { get; set; }
                public {{Types.String}}? {{OnValueChanged}} { get; set; }
            }
            """
        );
    }
}
